---
title: "Trabajo1"
author: "None"
date: "2023-03-17"
output: pdf_document
---

# 1er punto 
## a)

```{r,warning=FALSE}

library(ggplot2)
library(dplyr)
library(hrbrthemes)
generador <- function(cedula){
set.seed(cedula)
data <- rnorm(100)
data
}
times <- seq(1,100)
values <- generador(1007396943)
Datos = data.frame(times,values)
# Most basic bubble plot
p <- ggplot(Datos, aes(x=times, y=values)) +
geom_line( color="steelblue") +
geom_point() +
xlab("") +
theme_ipsum() +
theme(axis.text.x=element_text(angle=60, hjust=1))
p
```
## b)

```{r}
library(stats)

acf(Datos$values , main="ACF")
pacf(Datos$values, , main="PACF")


```

# 2 punto 
## a)

 Considere este proceso estacionario de media movil de orden 1 (MA(1)) 
 Z(t) = 0.9a(t-1) + a(t)
 
```{r}
a = Datos$values
# iniciando z#
z <- a
for (t in 2:100){
  z[t] <- 0.9 * a[t - 1] + a[t]
}

```

Graficando la trayectoria del proceso

```{r,warning=FALSE}
values2 <- z
Datos2 <- data.frame(times,values2)

p <- ggplot(Datos, aes(x=times, y=values2)) +
geom_line( color="red") +
geom_point() +
xlab("") +
theme_ipsum() +
theme(axis.text.x=element_text(angle=60, hjust=1))
p
```
 Considere este otro proceso estacionario de media movil de orden 1 (MA(1)) 
 Z(t) = -0.75a(t-1) + a(t)

```{r}
a = Datos$values
# iniciando z#
z2 <- a
for (t in 2:100){
  z2[t] <- -0.75 * a[t - 1] + a[t]
}
```

Graficando las realizaciones del proceso:

```{r,warning=FALSE}
values3 <- z2
Datos3 <- data.frame(times,values3)

p <- ggplot(Datos3, aes(x=times, y=values3)) +
geom_line( color="red") +
geom_point() +
xlab("") +
theme_ipsum() +
theme(axis.text.x=element_text(angle=60, hjust=1))
p

```

# b)

## ACF y PACF del primer proceso:

```{r}

acf(Datos2$values2)
pacf(Datos2$values2)

```

## ACF y PACF del segundo proceso:


```{r}
acf(Datos3$values3)
pacf(Datos3$values3)

```

# C)

## 1er grafico:

```{r}
plot(Datos$values,Datos2$values2, main = "Diagrama de Dispersión", 
     xlab = "Variable X", ylab = "Variable Y")
```

## 2do grafico

```{r}
plot(Datos$values, Datos2$values2, main = "Diagrama de Dispersión", 
     xlab = "Variable X", ylab = "Variable Y")
```





```{r}
# set.seed(123)
# n <- 100
# Z <- rep(0,n)
# for (i in 3:n) {
#   Z[i] <- 0.8*Z[i-1] - 0.3*Z[i-2] + rnorm(1)
# }
# plot(Z, type="l", col="steelblue")
```


```{r}
# Z[-1]
# Z
# length(Z[-1])
# length(Z)
```


```{r}
# par(mfrow=c(1,3))
# plot(Z[-100], Z[-1], xlab="Zt", ylab="Zt-1", col="steelblue")
# plot(Z[-1:-2], Z[-99:-2], xlab="Zt-2", ylab="Zt", col="steelblue")
# plot(Z[-1:-3], Z[-100:-2], xlab="Zt-3", ylab="Zt", col="steelblue")
```

```{r}
#z(t) = 0.1z(t-1) - 0.5z(t-2)+ a(t)
z <- rep(0,100)

z[1]<- a[1]
z[2] <- 0.1*z[2-1]-0.5*0 + a[2]

for(t in 3:100){
  simu <-  0.1*z[t-1] - 0.5*z[t-2] + a[t]
  z[t] <- simu
}

Datos2 <- data.frame(times,z)


p <- ggplot(Datos2, aes(x=times, y=z)) + 
  geom_line( color="steelblue") + 
  geom_point() + 
  xlab("Tiempo") + 
  theme_ipsum() + 
  theme(axis.text.x=element_text(angle=60, hjust=1))
p 


library(stats)
acf(Datos2$z)
pacf(Datos2$z)

```
##c
```{r}
zt_1 <- z
# zt_1[1] <- 0
# zt_1[2:100] <- z[1:99]

plot(z,lag(z,n=1), xlab="Zt", ylab="Zt-1", main= "Gráfico de dispersión Zt vs Zt-1", col= "blue")
```

```{r}

# zt_2 <- z
# zt_2[1] <- 0
# zt_2[2] <- 0
# zt_2[3:100] <- z[1:98]

plot(z,lag(z,n=2), xlab="Zt", ylab="Zt-1", main= "Gráfico de dispersión Zt vs Zt-2", col= "blue")

```

```{r}

zt_3 <- z
# zt_3[1] <- 0
# zt_3[2] <- 0
# zt_3[3] <- 0
# zt_2[4:100] <- z[1:97]

plot(z,lag(z,n=3), xlab="Zt", ylab="Zt-3", main= "Gráfico de dispersión Zt vs Zt-3", col= "blue")

```

